### ISSUE TITLE
i3-8100 SA6400调用核显出现故障

### ISSUE THREAD

**Issue by koihano** [moetayuko/intel-gpu-i915-backports#11]
环境：裸机SA6400
软件：emby 4.7.14.0 套件版，jellyfin 10.8.12 套件版
具体情况：
设置中已经识别出核显并有开启硬解的选项，但实际播放时查看解码信息没有进行硬解，切换码率时非常慢或者切换后无响应，如偶尔能正常播放则会间歇性出现色块错误，播放中CPU占用80%-90%。此外，调用核显后会无法正常关机（系统关闭后电源不会停止），或者系统崩溃自动重启。
日志：
[i915error.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13798671/i915error.txt)

**Comment by moetayuko** [comment]
1. 报错的位置非常奇怪，需要提供开机以来完整的 dmesg
2. emby 换成官网 beta 套件版，jellyfin 换成 https://hub.docker.com/r/nyanmisaka/jellyfin 再试

**Comment by koihano** [comment]
> 1. 报错的位置非常奇怪，需要提供开机以来完整的 dmesg
> 2. emby 换成官网 beta 套件版，jellyfin 换成 https://hub.docker.com/r/nyanmisaka/jellyfin 再试

第一条我如何配合您进行工作？
第二条我没有emby 4.8套件版的激活所以没法测试，jellyfin的话安装了上述docker版然后播放时切换码率会导致一直转圈圈无法读取，直到弹出没有兼容的流提示。

**Comment by moetayuko** [comment]
> 第一条我如何配合您进行工作？ 

`sudo dmesg > dmesg.txt`

**Comment by koihano** [comment]
> > 第一条我如何配合您进行工作？
> 
> `sudo dmesg > dmesg.txt`
[dmesg.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13800448/dmesg.txt)

**Comment by moetayuko** [comment]
> > > 第一条我如何配合您进行工作？
> > 
> > 
> > `sudo dmesg > dmesg.txt`
> > [dmesg.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13800448/dmesg.txt)

这份 log 看起来非常的正常。需要重启后复现一遍问题再输出 log

**Comment by koihano** [comment]
> > > > 第一条我如何配合您进行工作？
> > > 
> > > 
> > > `sudo dmesg > dmesg.txt`
> > > [dmesg.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13800448/dmesg.txt)
> 
> 这份 log 看起来非常的正常。需要重启后复现一遍问题再输出 log
[dmesg2.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13804113/dmesg2.txt)
[emby_log.zip](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13804114/emby_log.zip)

我尝试在emby中播放电影并切换码率，两部电影各重复操作三到四次

**Comment by moetayuko** [comment]
> > > > > 第一条我如何配合您进行工作？
> > > > 
> > > > 
> > > > `sudo dmesg > dmesg.txt`
> > > > [dmesg.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13800448/dmesg.txt)
> > 
> > 
> > 这份 log 看起来非常的正常。需要重启后复现一遍问题再输出 log
> > [dmesg2.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13804113/dmesg2.txt)
> > [emby_log.zip](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13804114/emby_log.zip)
> 
> 我尝试在emby中播放电影并切换码率，两部电影各重复操作三到四次

显卡驱动报错之前有一大堆 `PCIe Bus Error: severity=Corrected, type=Physical Layer`，所以看着不太像是显卡驱动本身的问题，可以依次尝试下列方案：
1. 升级 bios
2. 橡皮擦擦拭内存金手指
3. 启动参数添加 `pcie_aspm=off`（根据一份野教程 https://askubuntu.com/a/863301 ）
4. 裸机装 pve，在 pve 里装 dsm

**Comment by iovejieba** [comment]
qtj1同uhd630....emby beta套件状态下压根认不到核显 ...docker容器下 可以认到 但无法调用状态 
[dmesg.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13810716/dmesg.txt)
并且尝试了在xpenology发的那个测试固件问题依旧...jellyfin也如此

**Comment by moetayuko** [comment]
> qtj1同uhd630....emby beta套件状态下压根认不到核显 ...docker容器下 可以认到 但无法调用状态 [dmesg.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13810716/dmesg.txt) 并且尝试了在xpenology发的那个测试固件问题依旧...jellyfin也如此

你的 log 里没有任何报错，跟他的问题完全不同，别往这个 issue 下面凑

**Comment by iovejieba** [comment]
> > qtj1同uhd630....emby beta套件状态下压根认不到核显 ...docker容器下 可以认到 但无法调用状态 [dmesg.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13810716/dmesg.txt) 并且尝试了在xpenology发的那个测试固件问题依旧...jellyfin也如此
> 
> 你的 log 里没有任何报错，跟他的问题完全不同，别往这个 issue 下面凑

额 好吧....只是有很多10代已下的都有类似情况 我寻思过来issue下

**Comment by koihano** [comment]
> > > > > > 第一条我如何配合您进行工作？
> > > > > 
> > > > > 
> > > > > `sudo dmesg > dmesg.txt`
> > > > > [dmesg.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13800448/dmesg.txt)
> > > 
> > > 
> > > 这份 log 看起来非常的正常。需要重启后复现一遍问题再输出 log
> > > [dmesg2.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13804113/dmesg2.txt)
> > > [emby_log.zip](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13804114/emby_log.zip)
> > 
> > 
> > 我尝试在emby中播放电影并切换码率，两部电影各重复操作三到四次
> 
> 显卡驱动报错之前有一大堆 `PCIe Bus Error: severity=Corrected, type=Physical Layer`，所以看着不太像是显卡驱动本身的问题，可以依次尝试下列方案：
> 
> 1. 升级 bios
> 2. 橡皮擦擦拭内存金手指
> 3. 启动参数添加 `pcie_aspm=off`（根据一份野教程 https://askubuntu.com/a/863301 ）
> 4. 裸机装 pve，在 pve 里装 dsm

第一二条执行了以后再去播放故障依旧。然后wjz304大佬教我在rr的cmdline里面加上pcie_aspm=off，开机后查看了日志应该是已经关闭了，但使用emby播放依然没有调用核显转码。现在我将最后的日志发送给您，暂时先回到旧型号使用了。
[emby_log2.zip](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13815068/emby_log2.zip)
[dmesg7.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13815069/dmesg7.txt)

**Comment by moetayuko** [comment]
> 第一二条执行了以后再去播放故障依旧。然后wjz304大佬教我在rr的cmdline里面加上pcie_aspm=off，开机后查看了日志应该是已经关闭了，但使用emby播放依然没有调用核显转码。现在我将最后的日志发送给您，暂时先回到旧型号使用了。 [emby_log2.zip](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13815068/emby_log2.zip) [dmesg7.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13815069/dmesg7.txt)

这份确实有报错了，以前也有别人发过类似的，但我看不懂是什么问题

**Comment by peerless2012** [comment]
13代N100在SA6400上使用套件版jellyfin无法硬解，docker版正常硬解。

**Comment by moetayuko** [comment]
@koihano 试试 rr 24.2.0 能不能用

**Comment by koihano** [comment]
> @koihano 试试 rr 24.2.0 能不能用

看起来一切正常，除了emby切换码率有一半概率失灵，退出重进就好了。
[dmesg8.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/14151777/dmesg8.txt)

**Comment by moetayuko** [comment]
> > @koihano 试试 rr 24.2.0 能不能用
> 
> 看起来一切正常，除了emby切换码率有一半概率失灵，退出重进就好了。 [dmesg8.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/14151777/dmesg8.txt)

这个正常
