### ISSUE TITLE
[RFC] 悲报

### ISSUE THREAD

**Issue by moetayuko** [moetayuko/intel-gpu-i915-backports#12]
## 发生了啥

本仓库的上游项目 https://github.com/intel-gpu/intel-gpu-i915-backports 今日更新至 `I915-23.9.11` 版本，不完全移除了 12 代以前所有 GPU 的支持。该版本支持的 GPU 列表见 https://github.com/intel-gpu/intel-gpu-i915-backports/blob/afd4ae1704ae0ccb2a40a406a95783e3473dfd06/drivers/gpu/drm/i915/i915_pci.c#L622

所谓不完全移除，指的是移除了老设备的 PCI 设备号，但并没有彻底去掉分布在各个代码文件中针对这些设备的分支判断。也就是说，简单加回他们的设备号或许能让新驱动继续跑起来，但没有上游的技术支持，可能面临各种奇怪的 bug（虽然现状是上游早就不管 12 代以前设备了，这份驱动对他们的支持本来就有问题 #11 #4）

## 下一步怎么办

有以下选项，按我个人目前的偏好程度排序：
1. 跟随上游更新，放弃支持 12 代以前设备
    * 优点：工作量小，不容易引入额外 bug，对新设备支持更好
    * 缺点：除了不支持老设备外没有缺点。老设备交给 4.4 内核的 i915 处理
2. 跟随上游更新，但加回 4.4 内核不支持的设备（如果有的话）
    * 缺点：容易引入额外 bug，需要有人维护这些额外添加的设备
3. 切换上游至 https://github.com/intel/mainline-tracking/tree/linux/v6.5
    * 优点：这个分支是牙膏厂计划提交给主线的，看上去对新老设备都支持
    * 缺点：没有实际测试过，不知道兼容性到底如何。从更新频率来看对新设备的支
4. ~~切换上游至 https://github.com/torvalds/linux~~
    * 优点：靠谱
    * 缺点：不支持 SR-IOV，对新发布设备的支持不会太及时。等牙膏厂把 SR-IOV 提交到主线以后首选这个

**Comment by moetayuko** [comment]
Cc @wjz304 @Promix953

**Comment by wjz304** [comment]
![ec75c9a81fa7daa2e31f12fa44e349f1](https://github.com/MoetaYuko/intel-gpu-i915-backports/assets/5615843/1778f488-351a-4a15-adf0-ea7332257769)
...

**Comment by Promix953** [comment]
![mIq5qRyZMBxV9Bo76IJPH3PtVPWR6Lw2](https://github.com/MoetaYuko/intel-gpu-i915-backports/assets/22642692/59dc86a5-c255-43cf-9c3f-2b7890a1be2a)
...

**Comment by peerless2012** [comment]
HAHAHA,大佬们欲言又止。。。太操蛋了！

PS，还好我是N100，J4125和N5105这些用户就蛋疼了，是不是只能用回920了。

**Comment by moetayuko** [comment]
已选择方案三
