### ISSUE TITLE
N100在Proxmox-based DSM 7.2 for SA6400中调用SR-IOV核显解码失败，Windows 11虚拟机中Intel驱动安装完成后Error 43

### ISSUE THREAD

**Issue by everwisher** [moetayuko/intel-gpu-i915-backports#13]
- Hardware Build: 零刻EQ12 N100 Mini PC

- Proxmox Configuration:
   - `dpkg --list`: "intel-i915-dkms                      1.23.8.20.230810.22+i1-1            all          Out of tree i915 driver"
   - `lsmod | grep -I i915`:
       ```
       i915                 4349952  2
       intel_vsec             20480  1 i915
       compat                 24576  4 intel_vsec,mei,mei_me,i915
       drm_display_helper    229376  2 compat,i915
       drm_kms_helper        262144  2 drm_display_helper,i915
       cec                    90112  2 drm_display_helper,i915
       i2c_algo_bit           16384  1 i915
       drm                   729088  4 drm_kms_helper,drm_display_helper,i915
       video                  73728  1 i915
       ```
   - `modinfo i915`
      ```
       filename:       /lib/modules/6.5.11-7-pve/updates/dkms/i915.ko
       version:        backported to 6.5.11 from (b434e44e14397) using backports I915_23.8.20_PSB_230810.22
       ```
   - `/boot/grub/grub.cfg`:
      ```
       linux	/boot/vmlinuz-6.5.11-7-pve root=/dev/mapper/pve-root ro      quiet splash intel_iommu=on iommu=pt pcie_acs_override=downstream,multifunction i915.enable_guc=3 i915.max_vfs=7 rd.driver.blacklist=ahci,iwlwifi
       ```

- DSM Configuration

   - `ll /dev/dri:` <img width="453" alt="image" src="https://github.com/MoetaYuko/intel-gpu-i915-backports/assets/12667683/ed406655-e37b-47a2-898c-fef0c788ff00">

   - `dmesg | grep -i i915`:  <img width="884" alt="image" src="https://github.com/MoetaYuko/intel-gpu-i915-backports/assets/12667683/00f49687-c7a5-4d38-8d7b-42bf3397cae0">

使用Plex时手机客户端提示“Conversion failed. The transcoder exited due to an error"

**Comment by moetayuko** [comment]
emby beta 或 jellyfin 能解码吗？没用过 plex，不知道他打包的 vaapi 驱动支不支持 12 代

**Comment by everwisher** [comment]
因为有Plex pass，所以我没有用过那两个，但Windows 11上也是直通成功但驱动不起来，应该是同一个问题。

**Comment by moetayuko** [comment]
> 但Windows 11上也是直通成功但驱动不起来，应该是同一个问题。

应该不是
