### ISSUE TITLE
N100 SA6400调用核显出现故障

### ISSUE THREAD

**Issue by peerless2012** [moetayuko/intel-gpu-i915-backports#14]
环境：物理SA6400，7.2 beta4
软件：jellyfin 10.8.12 套件版
具体情况：
通过命令行已经能查到驱动，使用docker版jellyfin可以硬解（包括hevc和杜比视界），但是使用套件版无法启用硬解，不管是qsv还是vaapi都不行。

**Comment by moetayuko** [comment]
估计是套件版打包的 vaapi 驱动版本太老，请找对应开发者

**Comment by peerless2012** [comment]
新版本套件已解决。
