### ISSUE TITLE
SA6400机型如何手动更新i915驱动模块

### ISSUE THREAD

**Issue by PrestarLin** [moetayuko/intel-gpu-i915-backports#16]
现在rr已经删库，j3455机型安装sa6400，勾选了i915等相关驱动，屏幕会出现闪烁情况，请问该如何手动更新.ko文件呢，/usr/lib/modules/  目录里没有i915.ko

**Comment by octjim** [comment]
同问，是不是把包解压，放到/usr/lib/modules/ 和 /usr/lib/firmware/i915/ 目录中，改好权限就可以了？

**Comment by moetayuko** [comment]
https://github.com/MoetaYuko/intel-gpu-i915-backports/issues/15
