### ISSUE TITLE
An error occurred in pve, which does not affect use.

### ISSUE THREAD

**Issue by eleven702** [moetayuko/intel-gpu-i915-backports#19]
root@pve:~# dkms status
intel-i915-dkms/1.24.1.19.240119.1.nodrm, 6.8.4-2-pve, x86_64: installed

root@pve:~# dmesg |grep i915
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-6.8.4-2-pve root=/dev/mapper/pve-root ro quiet intel_iommu=on iommu=pt i915.enable_guc=3 i915.max_vfs=7
[    0.058418] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.8.4-2-pve root=/dev/mapper/pve-root ro quiet intel_iommu=on iommu=pt i915.enable_guc=3 i915.max_vfs=7
               use xe.force_probe='46b3' and i915.force_probe='!46b3'
[    2.312574] i915_compat: module verification failed: signature and/or required key missing - tainting kernel
[    2.812696] i915 0000:00:02.0: Running in SR-IOV PF mode
[    2.813238] i915 0000:00:02.0: [drm] VT-d active for gfx access
[    2.813262] i915 0000:00:02.0: vgaarb: deactivate vga console
[    2.813314] i915 0000:00:02.0: [drm] Using Transparent Hugepages
[    2.813697] i915 0000:00:02.0: vgaarb: VGA decodes changed: olddecodes=io+mem,decodes=io+mem:owns=io+mem
[    2.814369] mei_hdcp 0000:00:16.0-b638ab7e-94e2-4ea2-a552-d1c54b627f04: bound 0000:00:02.0 (ops i915_hdcp_ops [i915])
[    2.818363] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/adlp_dmc.bin (v2.20)
[    2.821473] i915 0000:00:02.0: [drm] GT0: GuC firmware i915/adlp_guc_70.bin version 70.20.0
[    2.821479] i915 0000:00:02.0: [drm] GT0: HuC firmware i915/tgl_huc.bin version 7.9.3
[    2.839006] i915 0000:00:02.0: [drm] GT0: HuC: authenticated for all workloads
[    2.839356] i915 0000:00:02.0: [drm] GT0: GUC: submission enabled
[    2.839357] i915 0000:00:02.0: [drm] GT0: GUC: SLPC enabled
[    2.839727] i915 0000:00:02.0: [drm] GT0: GUC: RC enabled
[    2.842129] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.0 on minor 0
[    2.843382] i915 display info: display version: 13
[    2.843383] i915 display info: cursor_needs_physical: no
[    2.843384] i915 display info: has_cdclk_crawl: yes
[    2.843385] i915 display info: has_cdclk_squash: no
[    2.843386] i915 display info: has_ddi: yes
[    2.843386] i915 display info: has_dp_mst: yes
[    2.843387] i915 display info: has_dsb: yes
[    2.843388] i915 display info: has_fpga_dbg: yes
[    2.843389] i915 display info: has_gmch: no
[    2.843390] i915 display info: has_hotplug: yes
[    2.843390] i915 display info: has_hti: no
[    2.843391] i915 display info: has_ipc: yes
[    2.843392] i915 display info: has_overlay: no
[    2.843392] i915 display info: has_psr: yes
[    2.843393] i915 display info: has_psr_hw_tracking: no
[    2.843394] i915 display info: overlay_needs_physical: no
[    2.843395] i915 display info: supports_tv: no
[    2.843395] i915 display info: has_hdcp: yes
[    2.843396] i915 display info: has_dmc: yes
[    2.843397] i915 display info: has_dsc: yes
[    2.843428] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[    2.843521] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[    2.843529] i915 0000:00:02.0: 7 VFs could be associated with this PF
[    2.843589] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    3.192725] i915 0000:00:02.0: vgaarb: VGA decodes changed: olddecodes=io+mem,decodes=none:owns=io+mem
               use xe.force_probe='46b3' and i915.force_probe='!46b3'
[    3.192815] i915 0000:00:02.1: enabling device (0000 -> 0002)
[    3.192858] i915 0000:00:02.1: Running in SR-IOV VF mode
[    3.193428] i915 0000:00:02.1: [drm] GT0: GUC: interface version 0.1.9.0
[    3.194119] i915 0000:00:02.1: [drm] VT-d active for gfx access
[    3.194141] i915 0000:00:02.1: [drm] Using Transparent Hugepages
[    3.194683] i915 0000:00:02.1: [drm] GT0: GUC: interface version 0.1.9.0

[2.843428] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[2.843521] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes

Are these two errors? How to fix

**Comment by eleven702** [comment]
Here's what I do:
git clone https://github.com/intel-gpu/intel-gpu-firmware.git

cd /root/intel-gpu-firmware/firmware
sudo mv *.bin /lib/firmware/updates/i915/

But the error mentioned above "[drm] Cannot find any crtc or sizes" still appears

**Comment by moetayuko** [comment]
no they aren't
