### ISSUE TITLE
rr自带核显驱动在plex里没有完全跑起来，核显占用很低，cpu占用很高

### ISSUE THREAD

**Issue by itnico** [moetayuko/intel-gpu-i915-backports#20]
大佬，请求帮忙
cpu:12500h，plex，rr-24.6.0
驱动装上了，但在plex里转码时，有看到提示（hw）硬件转码，但cpu占用很高，在intel_gpu_top里，核显占用很低

在13900h的机器里安装则没问题，核显占用很高，cpu几乎没占用。

请问如何解决？
谢谢

我的邮箱:itnico@163.com
QQ 1794639387

**Comment by moetayuko** [comment]
我既没有 plex pass 又没有 12500h 所以无法测试
