### ISSUE TITLE
绿联6800 Pro CPU i5 1235U  rr引导 安装SA6400 核显驱动不成功

### ISSUE THREAD

**Issue by RenXinIT** [moetayuko/intel-gpu-i915-backports#21]
![065ca9ea-ac24-43c5-a912-d87b4eb711cb](https://github.com/moetayuko/intel-gpu-i915-backports/assets/54830642/aa26f286-df21-46f5-bed0-4851f743475b)执行这两条命令的返回信息
，实际上没有驱动成功 emby jellyfin都调用不了

**Comment by moetayuko** [comment]
log?
