### ISSUE TITLE
UHD770核显 SR-IOV安装SA6400使用Jellyfin OpenCL色调映射问题

### ISSUE THREAD

**Issue by NJcoxx** [moetayuko/intel-gpu-i915-backports#24]
ProxmoxVE 8.2.2 QEMU Standard PC (Q35 + ICH9, 2009)
i7-12700 UHD770 Graphics
DSM
model: SA6400
version: DSM 7.2.1-69057 Update 5

UHD770核显SR-IOV安装SA6400使用Jellyfin OpenCL色调映射问题
虚拟机安装RR+DSM，CPU类型为host，VF拆分为7个，0000:00:02.2分配给虚拟机
在DSM环境下ls /dev/dri 可显示render128、card0

在Docker套件内使用nyanmisaka/jellyfin:latest及nyanmisaka/jellyfin:latest-legacy均出现以下问题：
在启用QSV硬件加速并开启OpenCL色调映射后，视频一直黑屏转圈无法播放(启用VPP映射无此问题)，进入终端后手动运行ffmpeg播放命令出现以下错误:

[Parsed_tonemap_opencl_3 @ 0x55c2f096ad80] Failed to wait for event completion: -14.
Segmentation fault (core dumped)

DSM的控制台内的报错
[ 1637.598660] i915 0000:04:00.0: [drm] GPU HANG: ecode 12:1:00000000, in ffmpeg [4276]
[ 1637.599260] i915 0000:04:00.0: [drm] ffmpeg[4276] context reset due to GPU hang
[ 1638.096094] ffmpeg[4276]: segfault at 178 ip 00007f959ea6ca14 sp 00007ffe3070a838 error 4 in libOpenCL.so.1.0.0[7f959ea69000+6000]
[ 1638.097285] Code: 66 0f 1f 44 00 00 ff a0 78 01 00 00 b8 dc ff ff ff c3 0f 1f 40 00 48 8b 05 f1 7b 00 00 48 85 c0 75 14 48 85 ff 74 15 48 8b 07 a0 78 01 00 00 66 0f 1f 44 00 00 ff a0 80 01 00 00 b8 dc ff ff

详细信息可以看https://github.com/RROrg/rr/issues/1222

**Comment by moetayuko** [comment]
如果 SR-IOV 有问题但直通正常的话大概率是陈年老 bug，得等牙膏厂自己修 https://github.com/strongtz/i915-sriov-dkms/issues/57

但是 i915 的 SR-IOV 目前仍然没进主线，估计进之前他们不会修
