### ISSUE TITLE
How intel-gpu-i915-backports uses the driver under Ubuntu for VMs

### ISSUE THREAD

**Issue by CWWK-TechnicalSupport** [moetayuko/intel-gpu-i915-backports#32]
As a question: does Ubuntu 22.04.05 and above drive the SR-IOV assigned kernel display just by installing it using the deb file from Release or does it require some other action?

**Comment by moetayuko** [comment]
you can use the upstream driver for ubuntu https://github.com/intel-gpu/intel-gpu-i915-backports
