### ISSUE TITLE
大佬，dpkg -i intel-i915-dkms_1.23.8.20.230810.22.6.2.0.34+i1-1_all.deb 以后如何查看驱动加载正常

### ISSUE THREAD

**Issue by OliLi1988** [moetayuko/intel-gpu-i915-backports#5]
大佬，dpkg -i intel-i915-dkms_1.23.8.20.230810.22.6.2.0.34+i1-1_all.deb 以后如何查看驱动加载正常

**Comment by OliLi1988** [comment]
Linux pve 6.5.11-6-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.11-6 (2023-11-29T08:32Z) x86_64 GNU/Linux
 使用  i915.enable_guc=3 i915.max_vfs=7 报错
[    4.284725] i915: unknown parameter 'max_vfs' ignored
[    4.285766] i915 0000:00:02.0: [drm] VT-d active for gfx access
[    4.285796] i915 0000:00:02.0: vgaarb: deactivate vga console
[    4.285850] i915 0000:00:02.0: [drm] Using Transparent Hugepages
[    4.286243] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
[    4.287623] mei_hdcp 0000:00:16.0-b638ab7e-94e2-4ea2-a552-d1c54b627f04: bound 0000:00:02.0 (ops i915_hdcp_ops [i915])
[    4.291278] i915 0000:00:02.0: [drm] Finished loading DMC firmware i915/adlp_dmc.bin (v2.20)
[    4.299672] i915 0000:00:02.0: [drm] GT0: GuC firmware i915/tgl_guc_70.bin version 70.13.1
[    4.299679] i915 0000:00:02.0: [drm] GT0: HuC firmware i915/tgl_huc.bin version 7.9.3
[    4.304108] i915 0000:00:02.0: [drm] GT0: HuC: authenticated for all workloads
[    4.304586] i915 0000:00:02.0: [drm] GT0: GUC: submission enabled
[    4.304589] i915 0000:00:02.0: [drm] GT0: GUC: SLPC enabled
[    4.304902] i915 0000:00:02.0: [drm] GT0: GUC: RC enabled
[    4.329366] mei_pxp 0000:00:16.0-fbf6fcf1-96cf-4e2e-a6a6-1bab8cbe36b1: bound 0000:00:02.0 (ops i915_pxp_tee_component_ops [i915])
[    4.329662] i915 0000:00:02.0: [drm] Protected Xe Path (PXP) protected content support initialized
[    4.331739] [drm] Initialized i915 1.6.0 20201103 for 0000:00:02.0 on minor 0
[    4.333313] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    4.333587] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[    4.333868] i915 0000:00:02.0: [drm] Cannot find any crtc or sizes
[    5.305031] i915 0000:00:02.0: driver does not support SR-IOV configuration via sysfs
[    5.305062] i915 0000:00:02.0: driver does not support SR-IOV configuration via sysfs

**Comment by moetayuko** [comment]
驱动没装上。6.5 内核需要使用今天下午新打包的驱动
