### ISSUE TITLE
冒昧打扰：十二代Intel N305 PVE8.1下开启SRIOV，分给群晖SA6400 7.2 i915报错

### ISSUE THREAD

**Issue by yuyeshun** [moetayuko/intel-gpu-i915-backports#6]
打扰大佬了，问下我是需要在PVE里安装新发布的intel-i915-dkms_1.23.8.20.230810.22+i1-1_all.deb吗？
群晖是使用RR 12.2引导安装的SA6400 7.2，最近使用RR升级到了12.3.
群晖报错如下：
~# dmesg | grep i915
[    0.000000] Command line: withefi dom_szmax=4094 earlyprintk syno_hw_version=SA6400 i915.enable_guc=3 console=ttyS0,115200n8 netif_num=2 synoboot2 pid=0x0001 earlycon=uart8250,io,0x3f8,115200n8 synoboot_satadom=-1 mac2=0011329be23a mac1=0011329be239 sn=V8YQ2J3B5IIZJ SMBusHddDynamicPower=1 vid=0x46f4 loglevel=15 skip_vender_mac_interfaces=0,1,2,3,4,5,6,7 panic=5 vender_format_version=2 log_buf_len=32M root=/dev/md0 syno_ttyS1=serial,0x2f8 syno_ttyS0=serial,0x3f8
[    0.095906] Kernel command line: withefi dom_szmax=4094 earlyprintk syno_hw_version=SA6400 i915.enable_guc=3 console=ttyS0,115200n8 netif_num=2 synoboot2 pid=0x0001 earlycon=uart8250,io,0x3f8,115200n8 synoboot_satadom=-1 mac2=0011329be23a mac1=0011329be239 sn=V8YQ2J3B5IIZJ SMBusHddDynamicPower=1 vid=0x46f4 loglevel=15 skip_vender_mac_interfaces=0,1,2,3,4,5,6,7 panic=5 vender_format_version=2 log_buf_len=32M root=/dev/md0 syno_ttyS1=serial,0x2f8 syno_ttyS0=serial,0x3f8
[    4.959293] i915 0000:06:10.0: Running in SR-IOV VF mode
[    4.960509] i915 0000:06:10.0: IOV0: Unable to confirm version 1.0 (0000000000000000)
[    4.961303] i915 0000:06:10.0: IOV0: Found interface version 0.1.0.0
[    4.962683] i915 0000:06:10.0: [drm] GT count: 1, enabled: 1
[    4.963381] i915 0000:06:10.0: [drm] Transparent Hugepage support is recommended for optimal performance on this platform!
[    4.967245] i915 0000:06:10.0: IOV0: Unable to confirm version 1.0 (0000000000000000)
[    4.968070] i915 0000:06:10.0: IOV0: Found interface version 0.1.0.0
[    4.969577] i915 0000:06:10.0: GuC firmware PRELOADED version 0.0 submission:SR-IOV VF
[    4.970227] i915 0000:06:10.0: HuC firmware PRELOADED
[    5.385372] i915 0000:06:10.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by intel_gt_init+0xe1/0x930 [i915]
[    5.401763] i915 0000:06:10.0: [drm:add_taint_for_CI [i915]] CI tainted:0x9 by i915_gem_init+0x14b/0x280 [i915]
[    5.405020] [drm] Initialized i915 1.6.0 20201103 for 0000:06:10.0 on minor 0
[    5.413284] i915 0000:06:10.0: [drm] PMU not supported for this GPU.

**Comment by moetayuko** [comment]
是，现在的 pve 驱动看起来不兼容

**Comment by yuyeshun** [comment]
感谢大佬，晚上回去装一下再试试。

**Comment by yuyeshun** [comment]
PVE里安装intel-i915-dkms_1.23.8.20.230810.22+i1-1_all.deb后，在RR 12.3版本下的SA6400 7.2成功实现核显SR-IOV的直通硬解。
i915日志如下
[    0.000000] Command line: withefi dom_szmax=4094 earlyprintk syno_hw_version=SA6400 i915.enable_guc=3 console=ttyS0,115200n8 netif_num=2 synoboot2 pid=0x0001 earlycon=uart8250,io,0x3f8,115200n8 synoboot_satadom=-1 mac2=0011329be23a mac1=0011329be239 sn=V8YQ2J3B5IIZJ SMBusHddDynamicPower=1 vid=0x46f4 loglevel=15 skip_vender_mac_interfaces=0,1,2,3,4,5,6,7 panic=5 vender_format_version=2 log_buf_len=32M root=/dev/md0 syno_ttyS1=serial,0x2f8 syno_ttyS0=serial,0x3f8
[    0.095872] Kernel command line: withefi dom_szmax=4094 earlyprintk syno_hw_version=SA6400 i915.enable_guc=3 console=ttyS0,115200n8 netif_num=2 synoboot2 pid=0x0001 earlycon=uart8250,io,0x3f8,115200n8 synoboot_satadom=-1 mac2=0011329be23a mac1=0011329be239 sn=V8YQ2J3B5IIZJ SMBusHddDynamicPower=1 vid=0x46f4 loglevel=15 skip_vender_mac_interfaces=0,1,2,3,4,5,6,7 panic=5 vender_format_version=2 log_buf_len=32M root=/dev/md0 syno_ttyS1=serial,0x2f8 syno_ttyS0=serial,0x3f8
[    5.188461] i915 0000:06:10.0: Running in SR-IOV VF mode
[    5.189538] i915 0000:06:10.0: GuC interface version 0.1.2.3
[    5.191054] i915 0000:06:10.0: [drm] GT count: 1, enabled: 1
[    5.191838] i915 0000:06:10.0: [drm] Transparent Hugepage support is recommended for optimal performance on this platform!
[    5.194074] i915 0000:06:10.0: GuC interface version 0.1.2.3
[    5.196510] i915 0000:06:10.0: GuC firmware PRELOADED version 1.2 submission:SR-IOV VF
[    5.197153] i915 0000:06:10.0: HuC firmware PRELOADED
[    5.202425] i915 0000:06:10.0: [drm] Protected Xe Path (PXP) protected content support initialized
[    5.203284] [drm] Initialized i915 1.6.0 20201103 for 0000:06:10.0 on minor 0
[    5.209205] i915 0000:06:10.0: [drm] PMU not supported for this GPU.

但是在群晖ssh里面使用
docker run --privileged --rm -it --entrypoint=/usr/bin/intel_gpu_top ghcr.io/xpenology-community/docker-intel-gpu-tools:latest
想查看核显使用率则会报错。之前直通核显的时候可以正常查看。
报错信息
Failed to detect engines! (No such file or directory)
(Kernel 4.16 or newer is required for i915 PMU support.)

在群晖ContainerManager里面可以运行起来这个容器，但是输入intel_gpu_top后同样报错。
<img width="628" alt="微信图片_20231208212814" src="https://github.com/MoetaYuko/intel-gpu-i915-backports/assets/12164615/22b2f012-0cb7-46a3-867e-69e72980ed4f">

**Comment by moetayuko** [comment]
所以能硬解吗？

**Comment by moetayuko** [comment]
我用这个工具也报一样的错，所以并不能说明什么问题。

**Comment by yuyeshun** [comment]
能硬解，没问题！
刚装了一下win11虚拟机，发现虚拟核显直通给win11，设备管理器里核显报错代码43。目前是说这套驱动只能给Linux/群晖用吗？

**Comment by moetayuko** [comment]
理论上没有这种限制，但我不知道 win 上匹配的驱动去哪下载

**Comment by yuyeshun** [comment]
https://www.derekseaman.com/2023/11/proxmox-ve-8-1-windows-11-vgpu-vt-d-passthrough-with-intel-alder-lake.html
之前我是照抄了这个的sriov，只能能给win不能给群晖

**Comment by tearsful** [comment]
@yuyeshun 兄弟， intel-i915-dkms_1.23.8.20.230810.22+i1-1_all.deb 这个安装包在哪能找到？
