### ISSUE TITLE
12代12100 pve8.0.4下开启sriov分配给群晖7.2有核显无法调用核显

### ISSUE THREAD

**Issue by H1447005189** [moetayuko/intel-gpu-i915-backports#9]
pve8.0.4开启了sriov，分配一个给window正常，一个给群晖，能看到核显但无法调用
<img width="215" alt="_a12206d7beb3b9642d24352422cc767c_-553872540_Cache_5ad8676f1a3959f8" src="https://github.com/MoetaYuko/intel-gpu-i915-backports/assets/111737191/60ff7f27-9c0f-4d1a-af96-d19952ac67b1">
，群晖型号sa6400，12.3引导，emby套件测试版，以下是emby日志，"Level": 40,
"Category": 0,
"Message": "Found 27 device entries"
}
]
}
 
,"ExitCode":0},"NvidiaCodecProvider":{"CodecProviderName":"NvidiaCodecProvider","StandardError":"ffdetect version 5.1-emby_2023_06_25 Copyright (c) 2018-2022 softworkz for Emby LLC\n built with gcc 10.3.0 (crosstool-NG 1.25.0)\n configuration: --cc=x86_64-emby-linux-gnu-gcc --prefix=/home/embybuilder/Buildbot/x64/ffmpeg-x64/staging --disable-alsa --disable-doc --disable-ffplay --disable-gnutls --disable-libpulse --disable-librtmp --disable-libxcb --disable-openssl --disable-vdpau --disable-vulkan --disable-xlib --enable-chromaprint --enable-fontconfig --enable-gpl --enable-iconv --enable-libaribb24 --enable-libass --enable-libdav1d --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --enable-mbedtls --enable-pic --enable-version3 --enable-libtesseract --enable-cuda-llvm --enable-cuvid --enable-libdrm --enable-libmfx --enable-nvdec --enable-nvenc --enable-vaapi --enable-opencl --enable-cross-compile --cross-prefix=x86_64-emby-linux-gnu- --arch=x86_64 --target-os=linux --enable-shared --disable-static --pkg-config=pkg-config --pkg-config-flags=--static --extra-libs='-lm -lstdc++ -lsharpyuv -pthread' --disable-debug\n libavutil 57. 28.100 / 57. 28.100\nCannot load libcuda.so.1\nError loading CUDA functions\n\n","Result":{
"ProgramVersion": {
"Version": "5.1-emby_2023_06_25",
"Copyright": "Copyright (c) 2018-2022 softworkz for Emby Llc",
"Compiler": "gcc 10.3.0 (crosstool-NG 1.25.0)",
"Configuration": "--cc=x86_64-emby-linux-gnu-gcc --prefix=/home/embybuilder/Buildbot/x64/ffmpeg-x64/staging --disable-alsa --disable-doc --disable-ffplay --disable-gnutls --disable-libpulse --disable-librtmp --disable-libxcb --disable-openssl --disable-vdpau --disable-vulkan --disable-xlib --enable-chromaprint --enable-fontconfig --enable-gpl --enable-iconv --enable-libaribb24 --enable-libass --enable-libdav1d --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libzvbi --enable-mbedtls --enable-pic --enable-version3 --enable-libtesseract --enable-cuda-llvm --enable-cuvid --enable-libdrm --enable-libmfx --enable-nvdec --enable-nvenc --enable-vaapi --enable-opencl --enable-cross-compile --cross-prefix=x86_64-emby-linux-gnu- --arch=x86_64 --target-os=linux --enable-shared --disable-static --pkg-config=pkg-config --pkg-config-flags=--static --extra-libs='-lm -lstdc++ -lsharpyuv -pthread' --disable-debug"
},
"Error": {
"Number": -1,
"Message": "Operation not permitted"
},
"Log": [
{
"Level": 16,
"Category": 0,
"Message": "Cannot load libcuda.so.1"
},
{
"Level": 16,
"Category": 0,
"Message": "Error loading CUDA functions"
}
]
}
 
,"ExitCode":1}},"FfmpegCapabilities":{"Version":"5.1-emby_2023_06_25"

**Comment by moetayuko** [comment]
日志不完整

**Comment by moetayuko** [comment]
此外已有朋友验证过 12100 可以正常 sriov

**Comment by H1447005189** [comment]
群晖显示显卡，但不调用，以下是详细日志，请大佬指教是哪的问题
[hardware_detection-63837666919.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13615573/hardware_detection-63837666919.txt)
[hardware_detection-63837666732.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13615574/hardware_detection-63837666732.txt)
[embyserver.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13615576/embyserver.txt)
[embyserver-63837666854.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13615577/embyserver-63837666854.txt)
[embyserver-63837666994.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13615578/embyserver-63837666994.txt)
[hardware_detection-63837666732.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13615580/hardware_detection-63837666732.txt)
[hardware_detection-63837666919.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13615581/hardware_detection-63837666919.txt)
[hardware_detection-63837667189.txt](https://github.com/MoetaYuko/intel-gpu-i915-backports/files/13615582/hardware_detection-63837667189.txt)

**Comment by moetayuko** [comment]
emby 是官网下的 beta 版吗，咋跟我的 ReleaseCode 不一样呢

**Comment by H1447005189** [comment]
是的，官网下的beta版https://github.com/MediaBrowser/Emby.Releases/releases/download/4.8.0.61/emby-server-synology72_4.8.0.61_x86_64.spk这个链接版本

**Comment by H1447005189** [comment]
大佬你是哪个版本，有链接吗，我试下你的版本

**Comment by moetayuko** [comment]
不知道这个啥毛病，试试 jellyfin

**Comment by H1447005189** [comment]
docker 安装emby beta版支持吗

**Comment by moetayuko** [comment]
不知道，我跟你是从同一个链接下的

**Comment by OliLi1988** [comment]
你在群晖下，dmesg |grep i915看一下显示什么不就知道了

**Comment by zg601x** [comment]
这个问题我也遇到了，我和题主配置差不多：PVE 8.1.3, CPU 13500, 虚拟群晖内核5.10.x，已包含移植的10-14代intel核显驱动。

PVE开启了核显sriov，不过我没有使用这个版本的dkms, 我使用的是https://github.com/strongtz/i915-sriov-dkms。

直通sriov核显（拆分后的核显之一）给win10，win11，没有问题，可以在任务管理器显示并正常使用。

直通sriov核显（拆分后的核显之一）给虚拟群晖，在虚拟机内，使用lspci可以看到对应的pci设备，类型0300，并且有了/dev/dri的设备文件，但是使用plex，jellyfin，套件版本、容器版本，均无法正常调用核显硬件硬解。

但是直通完整的核显（00:02.0）给虚拟群晖，一切正常。

**Comment by moetayuko** [comment]
> PVE开启了核显sriov，不过我没有使用这个版本的dkms, 我使用的是[https://github.com/strongtz/i915-sriov-dkms。](https://github.com/strongtz/i915-sriov-dkms%E3%80%82)

已知这个版本和 dsm 驱动不兼容，所以跟楼主的问题完全不一样，只是现象恰好相似而已

**Comment by zg601x** [comment]
> > PVE开启了核显sriov，不过我没有使用这个版本的dkms, 我使用的是[https://github.com/strongtz/i915-sriov-dkms。](https://github.com/strongtz/i915-sriov-dkms%E3%80%82)
> 
> 已知这个版本和 dsm 驱动不兼容，所以跟楼主的问题完全不一样，只是现象恰好相似而已

所以你修改的这个版本，可以与dsm驱动兼容是吗？我去试试

**Comment by zhifeng456** [comment]
@zg601x 老哥试过这个可以用吗

**Comment by zg601x** [comment]
> @zg601x 老哥试过这个可以用吗

没试，，，，估计不行吧，很多人遇到这问题了

**Comment by zhifeng456** [comment]
> > @zg601x 老哥试过这个可以用吗
> 
> 没试，，，，估计不行吧，很多人遇到这问题了
是的，我以前装的那个strongtz的，jellyfin发现解不了，LXC倒是没问题，MoetaYuko这个没试。

**Comment by zg601x** [comment]
> > > @zg601x 老哥试过这个可以用吗
> > 
> > 
> > 没试，，，，估计不行吧，很多人遇到这问题了
> > 是的，我以前装的那个strongtz的，jellyfin发现解不了，LXC倒是没问题，MoetaYuko这个没试。

等大神完美解决吧，估计只是时间问题

**Comment by moetayuko** [comment]
试试 rr 24.2.0 能不能用，pve 驱动也换成 release 里最新的

**Comment by zg601x** [comment]
> 试试 rr 24.2.0 能不能用，pve 驱动也换成 release 里最新的

大哥，你成功了吗

**Comment by moetayuko** [comment]
> > 试试 rr 24.2.0 能不能用，pve 驱动也换成 release 里最新的
> 
> 大哥，你成功了吗

我一直都是好的

**Comment by zg601x** [comment]
> > > 试试 rr 24.2.0 能不能用，pve 驱动也换成 release 里最新的
> > 
> > 
> > 大哥，你成功了吗
> 
> 我一直都是好的

你是十二代以上核显的sriov拆分直通给群晖吗？windows能不能调用？

我昨天试了最新的rr引导和最新的dkms，[https://github.com/strongtz/i915-sriov-dkms。](https://github.com/strongtz/i915-sriov-dkms这个版本的

**Comment by moetayuko** [comment]
windows 能不能用取决于 windows 驱动是否支持 sriov，跟本项目没有半毛钱关系
